feat: add withdraw for bundlr
metaplex-foundation/js-next pull request #80
Opened 2022-04-26 18:39 UTC by stranzhay

closes #46

2022-04-26 18:49 UTC, stranzhay commented
@lorisleiva  between `BundlrStorageDriver` `upload` and `uploadAll` i don't explicitly see those called anywhere in the app. It looks like `upload` calls `uploadAll` so I think it makes sense to do the withdraw there. What do you think of the `getLoadedBalance` on withdraw ?

2022-04-27 09:04 UTC, lorisleiva requested changes
Thanks for that, I've added some comments.

One concern I have here is that withdrawing after every upload messes up with some optimisations on the `uploadMetadata` operation.

This operation "pre-funds" with an estimation of all assets + metadata. Then it uploads twice. One for the assets and one for the metadata.

So if we withdraw after the first upload, we'll have to fund again before the second upload, which invalids the optimisation brought by the "pre-funding" step.

The reason for that "pre-funding" optimisation is that, on the browser, funding requires wallet approval. Therefore, by pre-funding, we reduce the amount of wallet pop-up the users have to go through to mint an NFT which is super valuable to the UX.

One solution to this would be to add a `withdraw = true` parameter to the upload methods but we can't do this because these methods are shared with other storage drivers that have no concept of funding or withdrawing. So we need to keep this Bundlr-specific.

I think the best thing to do would be to have a flag on the `BundlrStorageDriver` class directly like `shouldWithdrawAfterUploading` which defaults to true. Then we can have public methods such as `withdrawAfterUploading` and `dontWithdrawAfterUploading` that toggle that flag.

What do you think?

2022-04-27 18:36 UTC, stranzhay commented on src/drivers/storage/BundlrStorageDriver.ts
> +      await bundlr.withdrawBalance(balance);
It makes sense why you suggested that in the issue originally now. Also makes sense why i used to get errors on withdraw all the time  in my personal work lol

2022-04-28 02:02 UTC, stranzhay commented on src/drivers/storage/BundlrStorageDriver.ts
> +      throw new BundlrWithdrawError();
miss on my part for the draft

2022-05-04 14:52 UTC, lorisleiva approved these changes
@stranzhay I allowed myself to make a few changes so the upload plan uses the new withdrawal logic. Let me know what you think.

2022-05-04 16:34 UTC, merged